### ISSUE TITLE
problems in metadata

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#100]
http://toflit18.medialab.sciences-po.fr/#/exploration/meta

# colonne data  
## header 
select "source type" ou "direction" ou "products" ou "countries"
un deuxième select si "products" ou "countries" permettant de choisir une classification
## filtres 
mockup ok

# colonne viz 
- un histogramme montrant le nombre de direction par an
- une série d'histogramme un par valeur de ce qui a été choisi dans le header de data
chaque histogramme montre le nombre de flux contenant cette valeur par année.
Cette série d'histogramme n'est peuplée que si le nombre de valeurs possibles est inférieur à 20 ou 30 ?
voir #101 
- si pas trop long, ajouter une représentation (visuelle ou pas) de la clef de trie

# colonne legend
couleur du barchart 1 => nombre direction
couleur du barchart 2 => nombre de flux
ajotuer un paragraphe de texte : "barcharts are sorted by average number of flows per year"

**Comment by paulgirard** [comment]
Bout on export dans la légende.
Menu avec deux entrées pour les deux exports 
- export Direction by years 
- export Metadata

**Comment by paulgirard** [comment]
mockup fait, il faut intégrer à l'appli.

**Comment by jacomyal** [comment]
@paulgirard L'export "Metadata", il est censé contenir quoi comme données exactement ? Est-ce qu'il correspond à l'ancien export "Flows per year" ?

**Comment by paulgirard** [comment]
Il y a deux exports dans metadata.
Un export de l'histogramme du haut 'nombre de valeurs par année ' genre
nombre de direction.
Un export des histogrammes du bas 'nombre de flows par année' et par valeur.

Le 27 déc. 2017 4:29 PM, "Alexis Jacomy" <notifications@github.com> a
écrit :

**Comment by paulgirard** [comment]
pas mal de problèmes dans la metadata. Je note et on en parle
- [ ] le deuxième sélecteur en haut à gauche ne doit pas être présent pour SourceType
- [ ] le sélecteur de SourceType susnommé doit être dans les filtres comme pour direction
- [ ] les histogrammes des nombres de flux par année ne s'affichent plus
- [ ] on ne peut exporter que le nombre d'items par année
- [ ] le titre du barchart du haut (nombre d'items) est systématiquement "Total number of classified items per year" il faudrait adapter en fonction du choix du premier sélecteur: direction, Source type, product, countries

**Comment by paulgirard** [comment]
Testé marche parfaitement
