### ISSUE TITLE
network style

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#106]
- [x] direction des flèches cohérentes avec import ou export
- [ ] unifier le style graphique des réseaux (taille moyenne de edges et nodes) 
Pas sûr de comprendre cette item là en revanche ?

**Comment by jacomyal** [comment]
Je ne comprend pas non plus le second item, vu que Sigma est instancié avec les mêmes paramètres dans les deux visualisations.

Aussi, j'ai adapté la direction des flèches dans les deux visualisations, mais je ne suis pas sûr que ça soit pertinent dans la page "Product Terms Network". J'ai séparé les commits que ça soit facile à reverse, le cas échéant.

**Comment by paulgirard** [comment]
Non pas besoin de direction pour Product terms, d'ailleurs il n'ya pas de flèche dans mes tests sur cette vue.
On laisse tomber l'histoire de style que je ne comprends pas non plus.
Je clos donc.

**Comment by jacomyal** [comment]
Je rouvre pour penser à supprimer les flèches dans la page "Product Terms Network".

**Comment by gdaudin** [comment]
Hum... Ne s'agissait-il pas de désigner l'ordre des termes ? Mais c'est compliqué dans la mesure où cela peut être ambigu je pense.

De mémoire, le deuxième item portait sur le fait qu'il est important de pouvoir comparer deux représentations "par défaut" de deux réseaux différents. Comme les choses qui nous intéressent sont en relatif (on se doute que les termes du commerce de Marseille pour 1780 sont moins nombreux que ceux pour 1770-1780), cela devait être une demande pour que la taille moyenne des nœuds/liens soit la même dans la "première" vue de chaque réseau.
Mais c'est peut-être plus de travail que cela n'en mérite.

**Comment by paulgirard** [comment]
En effet la direction des liens est ambigüe pour les termes.
Ce serait au mieux difficile à comprendre.
Donc on met de côté.

Pour le deuxième point, pareil je ne suis pas sûr de comprendre.
Est ce que ça revient à dire que la taille du plus petit ou du plus gros noeuds/arc doit être toujours la même ?
Je pense que c'est déjà le cas.
On n'a plus vraiment le temps de creuser ce problème dans le cadre de cette mission je pense.
Mais on doit pouvoir adpater plus tard si on trouve une manière de mieux définri et donc résoudre le truc.

L'idéal serait sans doute que tu pointes deux screenshots avec les paramètres de query montrant le problème ? (dans une autre issue du coup)

**Comment by gdaudin** [comment]
Ok. Pas la peine que je fasse des screenshot avec la vieille version ? Je recommencerai avec la nouvelle.

**Comment by paulgirard** [comment]
oui exact
