### ISSUE TITLE
Ajout de permalinks dans les vues

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#111]
Idée de Robin. Le principe est de sauvegarder les filtres etc. de chaque vue dans la query de l'url afin de disposer de permaliens sur les vues et de pouvoir sauvegarder des vues etc. et d'y revenir facilement.

**Comment by paulgirard** [comment]
C'est loin d'être anodin parce qu'on n'a pas d'identifiants uniques mais on peut imaginer un système simple.
@Yomguithereal a des idées en ce sens

**Comment by gdaudin** [comment]
Sans la version des données -- plus un paramétrage de la vue

**Comment by paulgirard** [comment]
Pour ganrantir l'unicité des paramètres de requêtes on doit modifier l'import pour les noeuds de type :
- classification : hash = slug
- classificationGroup : hash = slug-slug(label)
- classificationItem : hash = slug-slug(label)
- direction : hash = slug(label)

On crée un hash unique qu'on stocke dans un paramètre id du noeud.
Il faut ajouter une contrainte du'nicité sur ce paramètre.
