### ISSUE TITLE
Viz "Exploration des flux"

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#112]
- Faire un module d'exploration des flux avec des filtres

- explorer les flux
    - c'est quoi les filtres (même que indicator) ?
    - est ce qu'on télécharge avec une limite
    - est ce que les vues renvoient vers cette exploration avec les mêmes filtres ?

**Comment by gdaudin** [comment]
Exploration de flux
Le datascape permet d’explorer les données en les agrégeant de diverses manières. Il manque une vue qui permettait de lister les données au niveau le plus fin, c’est à dire au niveau du flux de commerce annuel pour un produit un bureau et un partenaire donné. Une telle exploration permet de vérifier le détails des données ou de passer en revue l’hétérogénéité qui peut être masquée par les agrégations.
Cette interface d’exploration de flux prendra la même forme que les autres vues :
- un panel de filtrage à gauche (voir ci-dessous)
- une vue principale dans laquelle sont listées les fluxs sous la forme d’un tableau
- une pagination des résultats (non-indexée par page) permet de passer en revue de
nombreuses lignes
- un panel à gauche permet de choisir les colonnes à afficher et leur ordre (80 choix)
- les entêtes de colonnes permettent de choisir une clef de trie (ascendants,
descendants, inactif) (un seul critère actif à la fois)
Filtrage :
- années début - fin
- classification du country + choix d’un élément
- classification du produit
- import/export
- direction
- type de source
- par une valeur minimale
Liste des colonnes (non exhaustif) :
 
- année
- import/export
- direction
- type de source
- nom de la source
- page de la source (sheet)
- Produit une colonne par classification dont source
- Country une colonne par classification dont source
- valeur
- quantité
- unité
- prix unitaire
- remarques
- nom du transcripteur

**Comment by paulgirard** [comment]
Je ferme car on a découpé dans #179 #180 #181 #182 #183
