### ISSUE TITLE
Séparation contenu ou type d'action

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#119]
On passe à contenu.

Menu : Data : Metadata / Classification / Sources ajout d'un item Sources (qui sera une page web sur quelles sources et comment et ce que nous en avons fait). Les petits manuels, explication du rôle de Pierre Gervais, attention aux sources en doublon.

Menu : Explore trade : Les trois qui y sont.

Mettre «Explore trade» en premier

Glossary : Products / Concepts

About : User Guide / Github / History / Links and Publications / Credit / Contacts

**Comment by paulgirard** [comment]
#126
