### ISSUE TITLE
Le plein écran de viz product network ne marche pas

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#125]

**Comment by paulgirard** [comment]
@gdaudin What ?

**Comment by gdaudin** [comment]
Ma fourche a langué manifestement. Ce n'est pas clair dans mon esprit. En responsive ? En plein écran ?

**Comment by gdaudin** [comment]
Confirmé. Testé Chrome et Firefox sur Mac. Le bouton est là mais ne fait rien.

**Comment by sim51** [comment]
En prod & en local : fonctionne sur la page "Locations networks" avec firefox 81, mais pas sur la page "Product terms network"

**Comment by sim51** [comment]
En prod & en local : fonctionne sur la page "Locations networks" avec firefox 81, mais pas sur la page "Product terms network"
