### ISSUE TITLE
integrate new API classification

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#130]
Voici la doc de l'API pour le browser de classification après mise à jour.

# classification/:id/search

List/search groups of one classification with teh details of the list of items chich are aggregated by each group. The aggregation level can be set with queryItemFrom (default to the first parent classification).

##params
- **source** *?string* must be set to 'true' when querying the source classification (root of the classification tree) 
- **limit** *?string* limit the number of groups returned (default to 200 in default config)
- **offset** *?string* offset of groups pagination
- **queryGroup** *?string* pattern to search group name on
- **queryItem** *?string*  pattern to search item name on (ignored if source=true)
- **queryItemFrom** *?string* a classification id which must be a parent of :id to search items from
- **limitItem** *?string* limit the number of items in group (default to 5 in default config)
- **offsetItem** *?string* offset of items pagination (it has no sense in this root but well it exists)
- **orderBy** *?string* order by group list. Possible values are (Default to 'size') : 
   - 'size' =>  nbItems DESC
   - 'name' => name ASC
  -  'nbMatches' => nbMatchedItems DESC

##outputs
List of groups containing metadata + list of items.
matched info in both items and groups object are only present if queryItem exists ni query.
```json
{
    "status": "ok",
    "code": 200,
    "result": [
        {
            "name": "Metal products",
            "items": [
                {
                    "name": "potin à plomber pots",
                    "matched": true
                },
                {
                    "name": "Fer-blanc en quart",
                    "matched": false
                },
                {
                    "name": "acier",
                    "matched": false
                },
                {
                    "name": "acier brun",
                    "matched": false
                }
            ],
            "nbItems": 1601,
            "id": 615192,
            "nbMatchedItems": 1
        },
        {
            "name": "Linen threads and fabrics",
            "items": [
                {
                    "name": "toile de lin de Bernay",
                    "matched": true
                },
                {
                    "name": "batiste",
                    "matched": false
                },
                {
                    "name": "batiste blanche",
                    "matched": false
                },
                {
                    "name": "batiste et linon",
                    "matched": false
                }
            ],
            "nbItems": 430,
            "id": 615186,
            "nbMatchedItems": 1
        }
    ]
}
```
# classification/group/:id
List items of one classification group. API used to paginate over items in one group

##params
- **queryItem** *?string*  pattern to search item name on (ignored if source=true)
- **queryItemFrom** *?string* a classification id which must be a parent of :id to search items from
- **limitItem** *?string* limit the number of items in group (default to 5 in default api config)
- **offsetItem** *?string* offset of items pagination

##outputs
One group object containing metadata + list of items.
matched info in both items and group object are only present if queryItem exists in query.
```json
{
    "status": "ok",
    "code": 200,
    "result": {
        "name": "Metal products",
        "items": [
            {
                "name": "soufflets à tirer le vin",
                "matched": true
            },
            {
                "name": "soufflets à tirer le vin au clair",
                "matched": true
            },
            {
                "name": "soufflets à tirer le vin au clair avec sa garniture",
                "matched": true
            },
            {
                "name": "Fer-blanc en quart",
                "matched": false
            },
            {
                "name": "acier",
                "matched": false
            },
            {
                "name": "acier brun",
                "matched": false
            },
            {
                "name": "acier brut",
                "matched": false
            },
            {
                "name": "acier commun",
                "matched": false
            },
            {
                "name": "acier en barres",
                "matched": false
            },
            {
                "name": "acier en bottes pour la Compagnie des Indes",
                "matched": false
            }
        ],
        "nbItems": 1601,
        "id": 615192,
        "nbMatchedItems": 8
    }
}
```

**Comment by jacomyal** [comment]
Je push d'ici peu quelques petits correctifs pour l'API, mais j'ai toujours un peti soucis: Je n'ai pas les mêmes items ni le même nombre d'items via les routes `GET:/classification/:id/search` et `GET:/classification/group/:id`.

Exemples chez moi en local:

**`http://localhost:4000/classification/4/search?source=false`**

```json
{
  "status": "ok",
  "code": 200,
  "result": [
    {
      "name": "narrow medical product",
      "items": [
        {
          "name": "acide succinique"
        },
        {
          "name": "acorus"
        },
        {
          "name": "agaric"
        },
        {
          "name": "agaric amadouvier"
        },
        {
          "name": "agaric amadouvier brut"
        }
      ],
      "nbItems": 534,
      "id": 614575
    },
    {
      "name": "not a medical product",
      "items": [
        {
          "name": "???"
        },
        {
          "name": "??? blanc"
        },
        {
          "name": "??? brun"
        },
        {
          "name": "??? d'Anjou et de Touraine"
        },
        {
          "name": "??? d'une valeur moindre de deux mille francs chacun"
        }
      ],
      "nbItems": 19507,
      "id": 614574
    }
  ]
}
```

**`http://localhost:4000/classification/group/614575?limitItem=5&offsetItem=0`**

```json
{
  "status": "ok",
  "code": 200,
  "result": {
    "name": "narrow medical product",
    "items": [
      {
        "name": "///Drogues Médicinales///Drogues médicinales réunies",
        "matched": true
      },
      {
        "name": "///Drogues Médicinales///Drogues réunies",
        "matched": true
      },
      {
        "name": "///Drogues Médicinales///Ipécacuanha",
        "matched": true
      },
      {
        "name": "///Drogues Médicinales///Manne",
        "matched": true
      },
      {
        "name": "///Drogues Médicinales///Quinquina",
        "matched": true
      }
    ],
    "nbItems": 4044,
    "id": 614575
  }
}
```

**Comment by paulgirard** [comment]
en effet c'est un bug. Les items du group sont déclarées comme matched alors qu'il n'y a pas de query !
Je regarde

**Comment by paulgirard** [comment]
- [ ] bug chelou de l'api group
- [ ] ajouter nbResult à search
- [ ] order by ne marche pas

**Comment by paulgirard** [comment]
pour le nbResult, 
Jusqu'ici on n'en avait pas besoin car on avait un système de scroll infini qui n'a pas besoin de savoir le nombre de pages total.
Est ce vraiment indispensable puisque qu'on ne permet pas à l'utilisateur de changer de pages de résultats ?
Il ne peut faire que next non ? 
@jacomyal ton avis.

**Comment by paulgirard** [comment]
Pour le matched: true ce n'est pas trivial à virer.
Faut que je refacto. J'essaie de faire ça.

**Comment by jacomyal** [comment]
Pour le `nbResult`, je vais me débrouiller autrement : Quand l'utilisateur scroll et qu'un appelle renvoie 0 éléments, je vais set un flag. Ça va le faire.

Pour le `matched: true`, c'est pas trop grave : je peux simplement ne l'utiliser que si l'utilisateur a entré une requête. Mon principal soucis était que les items ne sont pas du tout les mêmes dans les 2 appels.

**Comment by paulgirard** [comment]
Ça devrait être fixé. Je te laisse clore une fois vérifier de ton côté.
