### ISSUE TITLE
Comportements des boîtes de texte dans «Classifications» 

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#137]
Quand je tape dans la boîte de recherche (au centre) une lettre avec accent circonflexe, j'ai "^ê" qui apparait au lieu de "ê".

Quand j'enlève une lettre au milieu d'un mot, mon curseur est renvoyé en fin de mot.

**Comment by gdaudin** [comment]
Testé aujourd’hui Firefox : toujours un souci, mais les lettres accentuées apparaissent.
Le curseur a un comportement chaotique. Voir dans cette vue http://toflit18.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_simplification&selectedParent=product_orthographic&queryGroup=%E9l%E9phant
Si je veux rajouter une lettre accentuée, le curseur va après l’insertion en fin de chaîne de caractère.
Si je veux effacer une lettre, le curseur va en fin de chaîne de caractère

**Comment by gdaudin** [comment]
Les lettres avec accent "ajouté" (comme "^" et "e" pour ê) n’apparaissent pas. Firefox mac aujourd’hui

**Comment by paulgirard** [comment]
A vérifier mais il me semble qu'il n'y a pas que dans classification que ce problème est présent mais dans tous les select.

**Comment by gdaudin** [comment]
Je viens de jeter un coup d’œil, et je n’ai pas vu le problème dans les boîtes de sélection de la colonne de gauche dans "Time Series", les networks ni métadata.

**Comment by paulgirard** [comment]
ok parfait. Merci d'avoir testé.

**Comment by paulgirard** [comment]
On a résolu le problème en enlevant le déclenchement automatique du search.

**Comment by gdaudin** [comment]
C’est bon pour moi.
