### ISSUE TITLE
accents, majuscule et ordre de tri

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#138]
Dans la viz "Classification", lorsqu'on choisi "Order by name", les lettres accentuées sont placées à la fin plutôt qu'après leurs compatriotes non-accentuées.

**Comment by paulgirard** [comment]
lié au #137 ?

**Comment by sim51** [comment]
Pour l'instant le tri se fait selon cet ordre : 
 * caratères spéciaux (ex: ?)
 * les majuscules
 * les majuscules accentuées
 * les minuscules
 * les minuscules accentuées

Quel serait l'ordre adequate selon vous ?

**Comment by gdaudin** [comment]
Je le prends du dictionnaire (quoique la norme ISO 14651:2019 et AFNOR NF Z44-001 sont peut-être à regarder ?)
Mais en gros, la principale chose qui me gène est que les lettres accentuées ne sont pas à côté de leurs équivalents non-accentués. Donc :
- Caractères spéciaux
- a minuscule
- A majuscule
- à minuscule
- À majuscule

J’ai trouvé cela chez les canadiens : http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4934

Est-ce que cela répond à votre question ?

**Comment by paulgirard** [comment]
Oui ça réponds.

**Comment by gdaudin** [comment]
Là, par exemple http://toflit18.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_revolutionempire&selectedParent=product_source

D’ailleurs, cela permet de voir un petit bug lié à l’affichage de la classification "source".  Mais je ne sais pas comment mettre une capture d’écran dans ce dialogue.

**Comment by gdaudin** [comment]
Et d’ailleurs je n’arrive pas à faire marcher le bouton "+" (zoom-in). C’est la première fois que je m’en rends compte.

**Comment by paulgirard** [comment]
Merci je valide donc que notre solution fonctionne.
Pour le + je confirme que ça coince en prod mais ça passe sur la version actuelle en local... 
Je te laisserai valider ça en testant la préprod

**Comment by gdaudin** [comment]
le "+" est aléatoire dans le pprd. (http://toflit18-pprd.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_revolutionempire&selectedParent=product_simplification la première catégorie, mais cela marche pour les autres.

**Comment by gdaudin** [comment]
http://toflit18-pprd.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_revolutionempire&selectedParent=product_simplification
"Ouvrages divers et mélangés" : Bengale ne devrait pas être en tête de classification.

**Comment by gdaudin** [comment]
http://toflit18-pprd.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_revolutionempire&selectedParent=product_simplification&queryGroup=vin

Madère ne devrait pas être en tête de la première catégorie.

**Comment by paulgirard** [comment]
Séparons les problèmes. Je crée une issue pour le bug du + : https://github.com/medialab/toflit18/issues/185

Pour l'ordre, tu parles donc de l'ordre des items. Je regarde.

**Comment by gdaudin** [comment]
Oui. Je crois que les groupes sont classés en ordre décroissants 
d’items ?

**Comment by paulgirard** [comment]
les groupes sont classés en fonctions de ce que demande le select.
Les items sont classés par ordre alphabétique sauf que neo4J utilise la méthode international qui ne te convient pas.
On a donc ajouté une méthode qui normalise les noms avant d'appliquer le order by du neo4j.
Ça devrait maintenant fonctionner comme tu le souhaites.

**Comment by gdaudin** [comment]
Oui, merci.
