### ISSUE TITLE
Exportation csv de la vue «Product Term Network»

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#147]

**Comment by gdaudin** [comment]
L'exportation donne la liste des nœuds liés à d'autres nœuds avec le nombre de flux entre eux. Il faudrait la changer dans trois directions : 
1) donner soit le nombre de flux, soit la valeur des flux, selon l'option choisie pour la viz pour l'utilisateur.
2) donner les information spécifique à chaque nœud (par exemple, le nombre/valeur des flux totaux, même ceux où le terme est seul.)
3) donner des informations sur les nœuds isolés, qui sont sur la viz mais pas dans l'export.

**Comment by gdaudin** [comment]
Oui, c'est sans doute ce que les utilisateurs cherchent, mais : 
- Cela ne correspond plus à l'esprit de la viz elle-même (ce qui n'est peut-être pas si grave)
- Cela ne permet pas de reconstruire la viz à partir de l'exportation sans travail de retraitement des données (cet argument me semble le meilleur). Or, c'est en partie le but de l'export.

**Comment by paulgirard** [comment]
On peut faire les deux

**Comment by paulgirard** [comment]
Je pense comme toi que le format de la viz est plutôt ce qui est attendu là.
On opte donc pour l'export du format réseau soit une liste des liens pondérés entre termes ?

**Comment by gdaudin** [comment]
Ok, donc on reste sur ce qui permet de refaire la viz.
Du coup, il faut une liste de liens pondérés entre termes, mais aussi une liste de terme (y compris les isolés) avec les informations spécifiques aux termes.
Bref, tout ce qui est envoyé à l’application qui dessine la viz, non ?

**Comment by paulgirard** [comment]
Oui à ce jour le navigateur ne reçoit que le réseau de termes et non les flux ayant servis à fabriquer le réseau.
Donc on peut facilement exporter la liste des termes et les liens entre eux pondérés.
Auquel cas cela veut dire deux exports : CSV des termes, CSV des liens entre termes

**Comment by gdaudin** [comment]
Est-ce qu’on peut / doit viser un format d’exportation du type pajek-net ? C’est du texte et c’est suffisamment structuré pour que l’utilisateur puisse le mettre facilement dans son logiciel d’analyse / représentation de réseau de son choix ?
https://gephi.org/users/supported-graph-formats/pajek-net-format/

En fait, je ne sais pas s’il y a un format standard pour les réseaux ? C’est cela qu’il faudrait utiliser (si c’est du texte).

Il y a des choses là  : https://gephi.org/users/supported-graph-formats/, mais je n’y connais rien...

**Comment by paulgirard** [comment]
oui on peut faire un format réseau mais ce sera moins pratique pour les gens qui veulent faire des stats. Auquel cas gexf.
tu préfère que ce soit facile à ouvrir dans gephi ou facile à ouvrir dans un tableur ?

**Comment by gdaudin** [comment]
Ah euh... J’hésite. Baba ou tiramisu ? Bon, égoïstement je dis tableur alors.
Après une vérification rapide, il me semble que les formats DL Ucinet ou Pajek ne peuvent pas faire double emploi si j’en crois https://gephi.org/users/supported-graph-formats/, ?

**Comment by paulgirard** [comment]
Pour le moment on a fait au plus vite en branchant ce qui existait pour location network.

**Comment by gdaudin** [comment]
Il faudrait aussi une liste de termes.

**Comment by paulgirard** [comment]
Dans ce cas le mieux est de faire deux export distinct un pour les noeuds/termes, l'autre pour les liens.

**Comment by gdaudin** [comment]
Oui, c’est peut-être le plus simple.

**Comment by gdaudin** [comment]
Et tant que nous sommes sur le sujet : il faudrait aussi exporter la couleur / community Louvain dans l’export des nœuds.

**Comment by paulgirard** [comment]
La couleur ou l'information de communauté ?

**Comment by gdaudin** [comment]
L’information

**Comment by gdaudin** [comment]
C’est cool ! Par contre, il me semble qu’on exporte deux fois la même colonne : la "size" et la "flow". En enlever une (ou m’expliquer ?)

**Comment by gdaudin** [comment]
Ok, pas grave
