### ISSUE TITLE
ajouter les descriptions des classifications

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#153]

**Comment by gdaudin** [comment]
J’hésite. Cela impose de créer du méta-data, mais après tout pourquoi pas. C’est bien de le mettre dans la prestation. Donc oui, à mettre avant le tableau de flux.

**Comment by sim51** [comment]
Le champ description est présent dans Neo4j et aussi renvoyé par l'API.
Donc il ne reste plus qu'a décider où l'afficher.

Voici une proposition d'affichage (j'ai encadré en rouge les changements) :

![image](https://user-images.githubusercontent.com/231657/94683740-47e91e80-0327-11eb-9bbb-d1ea60a2ac53.png)

**Comment by gdaudin** [comment]
- Je me demande si cela ne serait pas mieux plus bas.
Ou alors, ce qui me trouble est le gras en dessous de la description. Peut-être enlever le gras pour le nombre de groupes / items. Bon, je ne suis pas sûr...
- Bon, plus important  : la description n’est pas en dur, n’est-ce pas ? Le programme va la chercher dans "classifications_index.csv" à chaque mise à jour des données ? Si ce n’est pas le cas, ce serait bien que cela le soit.

**Comment by sim51** [comment]
Je confirme, la description vient du fichier `classifications_index.csv`.

**Comment by gdaudin** [comment]
Super. Reste la position : peut-être pouvons nous demander à Paul ce qu’il en pense ? @paulgirard

**Comment by sim51** [comment]
Je confirme, la description vient du fichier `classifications_index.csv`.

Sinon voici avec la description en bas  : 
![image](https://user-images.githubusercontent.com/231657/94785505-0a8c9b80-03d0-11eb-8a08-ead626267fa1.png)

Et l'option B,  la description au dessus sans le gras : 
![image](https://user-images.githubusercontent.com/231657/94785612-2e4fe180-03d0-11eb-85e3-4c6afbde3b5a.png)

Vous préférez quelle option ?

**Comment by gdaudin** [comment]
L’option B, mais je ne me fais pas très confiance.

**Comment by paulgirard** [comment]
+1 pour la B
