### ISSUE TITLE
récupérer le contenu du glossaire dans toflit18_data au format CSV

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#156]
Le contenu du glossaire est à ce jour contenu dans un ficheir json dans le code.
Le même contenu est édité par l'équipe de recherche dans le dépôt des données dans un csv.
- [x] définir un moyen de récupérer les données du glossaire depuis le dépôt de données
- [x] rebrancher le composant glossaire sur cette nouvelle source de données OU transformer le CSV au format JSON attendu

**Comment by sim51** [comment]
@gdaudin pouvez-vous préciser où se trouve le fichier CSV du glossaire dans le repository "toflit18_data" ?

**Comment by sim51** [comment]
est-ce ce fichier : https://github.com/medialab/toflit18_data/blob/a27c1acabfbd5b0570d15a494cc8964ec43f5206/base/01RepertoireMarchandises.csv ?

**Comment by gdaudin** [comment]
Oui, c’est bien lui

**Comment by gdaudin** [comment]
Je ne comprends pas : j’ai fais des modifications dans le staging de toflit18_data vendredi soir que j’ai pushée et je ne vois pas la modification sur le site. Commit 326791b2e8a7845f3cb457811e637afa20faf700.

**Comment by gdaudin** [comment]
J’avais réduit le nombre d’entrée "basin"

**Comment by paulgirard** [comment]
Il y a en effet un problème de choix de la branche. La versio staging du code va chercher le fichier CSV de la branche prod du github data.
En d'autres termes ta correction serait prise en compte en prod mais cela reste une anomalie qu'on va régler.
en staging ce doit être la version staging de data qui est chargée...

**Comment by gdaudin** [comment]
Cool !
