### ISSUE TITLE
Can't use terms network on source classif 404 from API

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#158]

**Comment by gdaudin** [comment]
@paulgirard C’est quoi ? Est-ce qu’on le met dans la presta ?

**Comment by gdaudin** [comment]
J’ai compris ! Paul regarde. Si c’est facile, il le change, sinon il le bloque.
http://toflit18.medialab.sciences-po.fr/#/exploration/terms?nodeSize=flows&edgeSize=flows&labelThreshold=3&labelSizeRatio=2&classification=product_source&sourceType=National%20best%20guess&direction=%24all%24&kind=total&dateMin=1750&dateMax=1750

**Comment by gdaudin** [comment]
En pprd, cela marche en product term.

http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/terms?nodeSize=flows&edgeSize=flows&labelThreshold=3&labelSizeRatio=2&classification=product_source&sourceType=National%20product%20best%20guess&direction=%24all%24&kind=total&dateMin=1750&dateMax=1750

Mais du coup, pourquoi pas sur location term ? On arrive à "No data to display"
http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/network?classification=partner_orthographic&sourceType=National%20product%20best%20guess&kind=total&dateMin=1750&dateMax=1750&nodeSize=flows&edgeSize=flows&labelThreshold=5&labelSizeRatio=2

**Comment by paulgirard** [comment]
Ah. Forcément il y a d'autres cas... Si tu en trouves d'autres je suis preneur. Je corrigerais dès que je m'y remets (très bientôt).

**Comment by paulgirard** [comment]
@gdaudin je ne reproduis pas ton problème sur la PPRD. L'URL que tu as mis marche. 
En revanche j'ai corrigé la metadata on pourra visualiser les produits des source.

**Comment by gdaudin** [comment]
@paulgirard http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/network?classification=partner_source&sourceType=National%20product%20best%20guess&kind=total&dateMin=1750&dateMax=1750&nodeSize=flows&edgeSize=flows&labelThreshold=5&labelSizeRatio=2 ?? Cela marche chez toi ? 
J’ai essayé Safari, Chrome et Firefox. Voici une des captures d’écran.
<img width="1420" alt="Capture d’écran 2020-10-14 à 10 38 08" src="https://user-images.githubusercontent.com/10850348/95964841-8bed2080-0e09-11eb-9f99-d7bb96b70cf8.png">

**Comment by gdaudin** [comment]
@paulgirard 

http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/meta?model=product&dataType=product_source

ne marche pas non plus chez moi d’ailleurs.

**Comment by gdaudin** [comment]
Bon, il faut peut-être que j’attende un peu pour ré-essayer...
