### ISSUE TITLE
Changer Best Guess (et les rendre paramétrable dans le code facilement)

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#173]
************For best guesses
capture drop national_product_best_guess
gen national_product_best_guess = 0		
replace national_product_best_guess = 1 if (sourcetype=="Objet Général" & year<=1786) | ///
		(sourcetype=="Résumé") | sourcetype=="National toutes directions tous partenaires" 

**Enlever Tableau des quantités

egen year_CN = max(national_product_best_guess), by(year)
replace national_product_best_guess=1 if year_CN == 1 & sourcetype=="Compagnie des Indes" & direction=="France par la Compagnie des Indes"

******************
capture drop national_geography_best_guess
gen national_geography_best_guess = 0
replace national_geography_best_guess = 1 if sourcetype=="Tableau Général" | sourcetype=="Résumé"

capture drop local_product_best_guess
gen local_product_best_guess=0
replace local_product_best_guess= 1 if (sourcetype=="Local" & year !=1750) | (sourcetype== "National toutes directions tous partenaires & year == 1750)

**Comment by gdaudin** [comment]
Le faire avec des flags à la construction des données ?

**Comment by gdaudin** [comment]
Faire un local geography

**Comment by gdaudin** [comment]
capture drop national_product_best_guess
gen national_product_best_guess = 0		
replace national_product_best_guess = 1 if (sourcetype=="Objet Général" & year<=1786) | ///
		(sourcetype=="Résumé") | sourcetype=="National toutes directions tous partenaires" 
egen year_CN = max(national_product_best_guess), by(year)
replace national_product_best_guess=1 if year_CN == 0 & sourcetype=="Compagnie des Indes" & direction=="France par la Compagnie des Indes"
drop year_CN

capture drop national_geography_best_guess
gen national_geography_best_guess = 0
replace national_geography_best_guess = 1 if sourcetype=="Tableau Général" | sourcetype=="Résumé"

capture drop local_product_best_guess
gen local_product_best_guess=0
replace local_product_best_guess= 1 if (sourcetype=="Local" & year !=1750) | (sourcetype== "National toutes directions tous partenaires & year == 1750)

capture drop local_geography_best_guess
gen local_geography_best_guess=0
replace local_geography_best_guess = 1 if sourcetype=="National toutes directions sans produits" | ///
		(sourcetype== "National toutes directions tous partenaires & year == 1750)
egen year_CN = max(local_geography_best_guess), by(year)
replace local_geography_best_guess=1 if year_CN == 0 & sourcetype=="Local"

**Comment by paulgirard** [comment]
Du coup les best guess actuels disparaissent ?

L'idée serait d'ajouter un flag avant la construction de la base soit dans le script python soit dans l'import.js.

Le problème ici est qu'on doit parcourir deux fois l'intégralité des flux pour appliquer les flags puisque la définition est récursive. 
Or aucun des scripts existants ne fait deux passes sur les données ni ne chargent tout en mémoire pour des raisons d'optimisation/ressources, il y a donc une petite difficulté d'architecture.

Par ailleurs cela demande de changer les morceaux du client et de l'API qui gèrent les "best guess".

**Comment by gdaudin** [comment]
Je vois pourquoi c’est compliqué, mais on a besoin de plus de flexibilité pour les best guess. Donc ajouter les flags semble mieux (même si cela va casser les morceaux qui gèrent)

**Comment by paulgirard** [comment]
C'est fait.
Le nouveau système est le suivant : 

1. le script python aggregate_sources_in_bdd_centrale_with_calculations.py ajoute les quatre variables best guess telles que définies ici
2. dans la base ces variables sont indexées sur chaque flux comme des flags booléens
3. dans le datascape ces variables sont utilisées comme des sourcetypes

Il n'est pas possible pour le moment de créer des nouvelles variables best guess directement depuis le script python. Le code d'import et le code du client web ont la liste de ces variables dans leur code.

**Comment by gdaudin** [comment]
Cela a l’air très bien. On ne peut pas créer de nouvelles variables, mais on peut adapter la définition des existantes via le code python, n’est-ce pas ?

**Comment by gdaudin** [comment]
Après vérification, c’est bon pour moi. Une raison de plus d’apprendre Python.
