### ISSUE TITLE
Être tolérant avec les apostrophes.

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#178]
Dans cette vue  : http://toflit18.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_simplification&selectedParent=product_orthographic&queryGroup=veret%20crist

Dans "simplification" "Dents d’éléphants" ne trouve rien, alors que "Dents d'éléphants" donne ce qu’il faut.
L’apostrophe n’est pas le même caractère ASCII.

**Comment by paulgirard** [comment]
Il s'agit d'un comportement normal d'après moi.
Chaque caractère est cherché exactement.
Si tu veux pouvoir accepter d'autres caractères il est possible d'utiliser le "."
"dents d.éléphant"

Je ne vois pas quelle serait la solution que tu souhaites mettre en place ? 
Remplacer les apostrophes vers la version simple ? Interdire les caractères non lettre ? Mais si on le fait pour les apostrophes pourquoi ne pas le faire sur les espaces insécables ou autre... Ce qui me parraît peser du côté "trop de magie" et ajouter du code pour peu de gain.
La solution actuelle ayant le mérite d'être simple à expliquer.

**Comment by gdaudin** [comment]
Oui, je vois le problème pour les apostrophes. Je crois que c’est lié au fait que j’utilise un Bépo et qu’ils ont décidé d’utiliser « ’ » plutôt que « ‘ » comme apostrophe. Du coup, il vaut mieux que le datascape marche avec l’apostrophe standard des claviers Francais Azerty, et c’est la situation actuelle.

https://bepo.fr/wiki/Apostrophe
