### ISSUE TITLE
Viz "Exploration des flux" -- Filtrage

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#179]
Exploration de flux
Le datascape permet d’explorer les données en les agrégeant de diverses manières. Il manque une vue qui permettait de lister les données au niveau le plus fin, c’est à dire au niveau du flux de commerce annuel pour un produit un bureau et un partenaire donné. Une telle exploration permet de vérifier le détails des données ou de passer en revue l’hétérogénéité qui peut être masquée par les agrégations.

ici, PANEL DE FILTRAGE

- un panel de filtrage à gauche (voir ci-dessous)
Filtrage :
- années début - fin
- classification du country + choix d’un élément
- classification du produit
- import/export
- direction
- type de source
- par une valeur minimale

**Comment by paulgirard** [comment]
Filtrages listés ici : done.

**Comment by paulgirard** [comment]
Si on choisit une classification sans item : mettre la colonne mais ne pas filtrer.
