### ISSUE TITLE
Viz Exploration des flux -- tableau paginé

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#180]
Exploration de flux
Le datascape permet d’explorer les données en les agrégeant de diverses manières. Il manque une vue qui permettait de lister les données au niveau le plus fin, c’est à dire au niveau du flux de commerce annuel pour un produit un bureau et un partenaire donné. Une telle exploration permet de vérifier le détails des données ou de passer en revue l’hétérogénéité qui peut être masquée par les agrégations.
Cette interface d’exploration de flux prendra la même forme que les autres vues :
- un panel de filtrage à gauche (voir ci-dessous)
- une vue principale dans laquelle sont listées les fluxs sous la forme d’un tableau
- une pagination des résultats (non-indexée par page) permet de passer en revue de
nombreuses lignes
- un panel à gauche permet de choisir les colonnes à afficher et leur ordre (80 choix)
- les entêtes de colonnes permettent de choisir une clef de trie (ascendants,
descendants, inactif) (un seul critère actif à la fois)

Liste des colonnes (non exhaustif) :
 
- année
- import/export
- direction
- type de source
- nom de la source
- page de la source (sheet)
- Produit une colonne par classification dont source
- Country une colonne par classification dont source
- valeur
- quantité
- unité
- prix unitaire
- remarques
- nom du transcripteur

**Comment by gdaudin** [comment]
from PG  : # pagination

C'est indispensable de paginer car le nombre de flux est très grand.
Au delà du temps, le navigateur exploserait si on affichait tout.

Pour paginer on peut faire un mode suivant/précédant ou en pages
indexées (1-2-3..). L'indexation demande de connaître à priori le
nombre total de flux ce qui fait un calcul coûteux (sans être fou) de
plus.
On serait parti sur suivant/précédent sauf si tu souhaites par ailleurs
tu que ce soit possible d'afficher le nombre de flux total répondant
aux filtres ?

**Comment by gdaudin** [comment]
Ok pour paginer indexé car le résultat est important.
Le temps d’attente pour les pages qui sont en fin de liste sera long (car il faut tout repaginer)

**Comment by gdaudin** [comment]
Mettre le numéro de page dans l’url pérenne si possible

**Comment by paulgirard** [comment]
Le tableau paginé fonctionne.
La pagination est pour le moment faites en previous/next.
On pourrait imaginer le faire en scroll mais ça demande un développement important en plus.
A discuter

**Comment by paulgirard** [comment]
formattage : aligner les valeurs sur le premier chiffre non décimal
