### ISSUE TITLE
Viz - Exploration des flux Export

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#183]
Exploration de flux
Le datascape permet d’explorer les données en les agrégeant de diverses manières. Il manque une vue qui permettait de lister les données au niveau le plus fin, c’est à dire au niveau du flux de commerce annuel pour un produit un bureau et un partenaire donné. Une telle exploration permet de vérifier le détails des données ou de passer en revue l’hétérogénéité qui peut être masquée par les agrégations.

Ici, export en CSV

**Comment by gdaudin** [comment]
PG  : Il est souhaitable de limiter l'export pour ne pas faire exploser la
mémoire du navigateur. Il y a plusieurs façon de faire. Le plus simple
serait de fixer une limite haute (on fera des tests) fixe et de
prévenir l'utilisateur quand on a dû couper et l'inviter à aller
récupérer les données sur github.
L'utilisateur pourrait tenter de tout récupérer en utilisant un filtre
de plus pour découper son paquet de flux.
Ça t'irait ?

**Comment by gdaudin** [comment]
Oui. Je crois que le mieux est de l’empêcher (bouton disabled s’il y a trop de flux). Il faut donner la limite.

**Comment by paulgirard** [comment]
posssible car on a décidé de calculer le nombre de flux.
