### ISSUE TITLE
Limite de nombre de courbes dans "Times Series" sans avertissement

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#187]
Il n’est pas possible de dépasser 6 lignes dans "Time Series". I.e. quand on est là, on ne peut pas en rajouter. Quand on clique "update", rien ne se passe.

Ce serait bien que la limite soit plus élevée, sans être indispensable.
Par contre, je pense qu’il est indispensable de signaler cette limite quelque part. Un petit message après avoir cliqué "update", par exemple ?

http://toflit18.medialab.sciences-po.fr/#/exploration/indicators?lines=%5B%7B%22color%22%3A%22%23C14F4C%22%2C%22sourceType%22%3A%22National%20product%20best%20guess%22%7D%2C%7B%22color%22%3A%22%23504342%22%2C%22sourceType%22%3A%22National%20toutes%20directions%20partenaires%20manquants%22%7D%2C%7B%22color%22%3A%22%23A563B7%22%2C%22sourceType%22%3A%22National%20toutes%20directions%20sans%20produits%22%7D%2C%7B%22color%22%3A%22%2385C85B%22%2C%22sourceType%22%3A%22National%20toutes%20directions%20tous%20partenaires%22%7D%2C%7B%22color%22%3A%22%2394B8B7%22%2C%22sourceType%22%3A%221792-both%20semester%22%7D%2C%7B%22color%22%3A%22%23B89648%22%2C%22sourceType%22%3A%221792-first%20semester%22%7D%5D

@paulgirard je te laisse voir si cela mérite d’être mis dans ce milestone ?

**Comment by paulgirard** [comment]
- button disabled if two many lines
- maximum number of lines in specs.json file
- Two messages explains why the Add line button is disabled ![image](https://user-images.githubusercontent.com/193478/98001342-d00e8800-1ded-11eb-9b9f-77bc18c00ced.png)
