### ISSUE TITLE
Pourquoi est-ce que 49, 51, 53 sont indiquées présentes dans best_guess_department_prodxpart pour Amiens ?

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#191]
Là :http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/meta?model=direction&sourceType=Best%20Guess%20tax%20department%20product%20x%20partner

Il ne devrait y avoir que 1750

**Comment by paulgirard** [comment]
![image](https://user-images.githubusercontent.com/193478/97994915-27a8f580-1de6-11eb-9810-afde3a30552e.png)
Un oubli pendant la refacto du lowercase
