### ISSUE TITLE
Explorateur de flux : le tri par valeur ne marche pas

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#192]
Là  : 
http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20national%20product%20x%20partner&productClassification=product_sitc_EN&product=%5B%22Raw_materials%2C_inedible%2C_except_fuels%7Eproduct_sitc_EN%22%5D&page=0&direction=%24all%24&kind=total&dateMin=1720&dateMax=1780&columns=%5B%22product%22%2C%22direction%22%2C%22year%22%2C%22partner%22%2C%22import%22%2C%22value%22%2C%22source%22%5D&orders=%5B%7B%22key%22%3A%22value%22%2C%22order%22%3A%22DESC%22%7D%5D

**Comment by paulgirard** [comment]
corrigé à vérifier
