### ISSUE TITLE
Explorateur de flux : les URL pérennes ne marchent pas

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#193]
Voir http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20national%20product%20x%20partner&productClassification=product_sitc_EN&product=%5B%22Raw_materials%2C_inedible%2C_except_fuels%7Eproduct_sitc_EN%22%5D&page=0&direction=%24all%24&kind=total&dateMin=1720&dateMax=1780&columns=%5B%22product%22%2C%22direction%22%2C%22year%22%2C%22partner%22%2C%22import%22%2C%22value%22%2C%22source%22%5D&orders=%5B%7B%22key%22%3A%22value%22%2C%22order%22%3A%22DESC%22%7D%5D

et 

http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20tax%20department%20product%20x%20partner&productClassification=product_grains&product=%5B%22C%E9r%E9ales_inf%E9rieures_%282%29%7Eproduct_grains%22%2C%22Froment_%281%29%7Eproduct_grains%22%2C%22Menus_grains_%283%29%7Eproduct_grains%22%2C%22Grains_transform%E9s_%285%29%7Eproduct_grains%22%2C%22re%3A%3A4%22%5D&page=0&direction=%24all%24&kind=import&dateMin=1770&dateMax=1770&columns=%5B%22product%22%2C%22direction%22%2C%22partner%22%2C%22value%22%2C%22quantity%22%2C%22source%22%2C%22unitPrice%22%5D&orders=%5B%7B%22key%22%3A%22value%22%2C%22order%22%3A%22ASC%22%7D%5D

**Comment by paulgirard** [comment]
duplicates #199 (corrigé à vérifier)

**Comment by gdaudin** [comment]
Oui, les liens fonctionnent en effet. Merci !
