### ISSUE TITLE
Explorateur de flux :comment voir dans une colonne qui n’est pas assez large ?

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#194]
Par exemple Source filepath dans la vue par défaut ?

**Comment by paulgirard** [comment]
Find a way to make the resize action zone more identifiable by users.
Increase the salience.
change color and.or add a dragable zone on the left side of the header too.

**Comment by gdaudin** [comment]
Ça non plus, cela n’a pas été fait, mais, bon, tant pis.

**Comment by gdaudin** [comment]
Si, ça éfé fait (il y a même un tooltip)
