### ISSUE TITLE
Explorateur des flux : il n’y a pas d’ascenceur horizontal pour voir les autres colonnes

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#195]

**Comment by paulgirard** [comment]
pas de scroll horizontal sous Google Chrome sous linux.
pas de scroll non plus sous mac sosu firefox et chrome

**Comment by gdaudin** [comment]
On renonce pour l’instant.

**Comment by paulgirard** [comment]
CSS nightmare : 
- linux chrome : horizontal scroll should be always visible
- firefox linux: if columns width changes, vertical scroll bar disapears

**Comment by gdaudin** [comment]
Salut ! J’arrive à scroller, mais pas à réduire la taille d’une colonne. Et en plus, la largeur ne se reset pas lorsqu’on enlève et remet la variable.

**Comment by gdaudin** [comment]
Firefox Mac : le horizontal scroll n’est pas visible. Mais on peut scroller à 2 doigts (pas à la souris)
Idem Safari Mac.

**Comment by paulgirard** [comment]
arf.

**Comment by gdaudin** [comment]
Traité en partie par Paul a datasprint Marseille

**Comment by gdaudin** [comment]
Réponse paul : J'ai aussi réglé le problème de la barre de défilement horizontale dans le tableau des flux.

Oui, je viens de tester en stagging : j’ai bien la barre de défilement horizontale. Merci !
