### ISSUE TITLE
Explorateur de flux : la devise passe en Fr de manière aléatoire

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#197]
Dur à reproduire...

**Comment by gdaudin** [comment]
Ah, si... Là par exemple : http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20tax%20department%20product%20x%20partner&productClassification=product_grains&product=%5B%22C%E9r%E9ales_inf%E9rieures_%282%29%7Eproduct_grains%22%2C%22Froment_%281%29%7Eproduct_grains%22%2C%22Menus_grains_%283%29%7Eproduct_grains%22%2C%22Grains_transform%E9s_%285%29%7Eproduct_grains%22%2C%22re%3A%3A4%22%5D&page=0&direction=%24all%24&kind=import&dateMin=1770&dateMax=1770&columns=%5B%22product%22%2C%22direction%22%2C%22partner%22%2C%22value%22%2C%22quantity%22%2C%22source%22%2C%22unitPrice%22%5D&orders=%5B%7B%22key%22%3A%22value%22%2C%22order%22%3A%22ASC%22%7D%5D

**Comment by gdaudin** [comment]
Mais pas là.... Bizarre. http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20tax%20department%20product%20x%20partner&productClassification=product_grains&product=%5B%22C%E9r%E9ales_inf%E9rieures_%282%29%7Eproduct_grains%22%2C%22Froment_%281%29%7Eproduct_grains%22%2C%22Menus_grains_%283%29%7Eproduct_grains%22%2C%22Grains_transform%E9s_%285%29%7Eproduct_grains%22%2C%22re%3A%3A4%22%5D&page=0&direction=%24all%24&kind=import&dateMin=1770&dateMax=1770&columns=%5B%22product%22%2C%22direction%22%2C%22partner%22%2C%22value%22%2C%22year%22%2C%22quantity%22%2C%22source%22%2C%22unitPrice%22%5D&orders=%5B%5D

**Comment by gdaudin** [comment]
le bug est toujours là, mais on vit avec ?

**Comment by paulgirard** [comment]
celle là elle marche : http://toflit18.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20customs%20region%20product%20x%20partner&productClassification=product_grains&product=%5B%22Froment_%281%29%7Eproduct_grains%22%2C%22Menus_grains_%283%29%7Eproduct_grains%22%2C%22C%E9r%E9ales_inf%E9rieures_%282%29%7Eproduct_grains%22%2C%22Substituts_%284%29%7Eproduct_grains%22%2C%22Pas_grain_%280%29%7Eproduct_grains%22%2C%22Grains_transform%E9s_%285%29%7Eproduct_grains%22%5D&page=6&kind=import&dateMin=1770&dateMax=1770&columns=%5B%22product%22%2C%22region%22%2C%22year%22%2C%22partner%22%2C%22import%22%2C%22value%22%2C%22source%22%5D

**Comment by paulgirard** [comment]
Le problème est qu'on utilise l'année pour déterminer quelle est la devise lt. avant 1797.
Or si la colonne Year n'est pas sélectionnée les données d'année ne sont pas incluses dans le résultat et on affiche par défaut Fr.

J'ai ajouté le champs Year systématiquement aux données renvoyées par l'API qu'on choisisse cette colonne ou non. Ainsi la donnée est présente pour déterminer la devise mais ne s'affiche que si on demande à voir la colonne.

Ajouter la devise dans les données pourrait être une meilleure solution. À méditer.

**Comment by gdaudin** [comment]
En tous les cas, cela semble bon : merci !
