### ISSUE TITLE
FLOWS: Echec de mise à jour

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#199]
Nantes / grains / mais pas "Local".
http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?productClassification=product_grains&product=%5B%22Froment_%281%29%7Eproduct_grains%22%2C%22C%E9r%E9ales_inf%E9rieures_%282%29%7Eproduct_grains%22%2C%22Menus_grains_%283%29%7Eproduct_grains%22%2C%22Substituts_%284%29%7Eproduct_grains%22%2C%22Grains_transform%E9s_%285%29%7Eproduct_grains%22%5D&page=0&direction=Nantes&kind=export&dateMin=1766&dateMax=1766&columns=%5B%22product%22%2C%22direction%22%2C%22year%22%2C%22partner%22%2C%22import%22%2C%22value%22%2C%22source%22%5D&orders=%5B%7B%22key%22%3A%22value%22%2C%22order%22%3A%22DESC%22%7D%2C%7B%22key%22%3A%22product%22%2C%22order%22%3A%22ASC%22%7D%5D

**Comment by paulgirard** [comment]
corrigé à valider

**Comment by gdaudin** [comment]
Cela est résolu, je pense ?
