### ISSUE TITLE
Gros bug : il manque au moins un flux dans le datascape

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#200]
Importation de froment d’Italie en 1771 pour Objet Général ("line number 148"). C’est un double account  : est-ce que le problème vient de là ?. Cela semble être la cas, car il manque aussi un flux du Nord et un flux de Savoie, qui sont dans le même cas. 
br if year ==1771 & source_type=="Objet Général" & export_import=="Imports" & product_grains=="Froment (1)" donne 19 flux.

http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/flows?sourceType=Best%20Guess%20national%20product%20x%20partner&productClassification=product_grains&product=%5B%22Froment_%281%29%7Eproduct_grains%22%5D&page=0&direction=%24all%24&kind=import&dateMin=1771&dateMax=1771&columns=%5B%22product%22%2C%22direction%22%2C%22year%22%2C%22partner%22%2C%22import%22%2C%22value%22%2C%22source%22%5D&orders=%5B%7B%22key%22%3A%22partner%22%2C%22order%22%3A%22ASC%22%7D%5D en donne 16...

**Comment by paulgirard** [comment]
Oui les doubleaccounts sont ignorés : 
```javascript
  // Handling double accounts
  if (csvLine.value_part_of_bundle && +csvLine.value_part_of_bundle > 1) return;
```

**Comment by gdaudin** [comment]
Ah bah il ne faudrait pas…

**Comment by gdaudin** [comment]
La valeur du flux est indiquée dans la « dernière » double account 
(surtout 2, mais aussi 3 ou 4). Je peux tout passer en 1 pour régler le 
problème d’un coup de baguette magique. Mais pour avoir les 
quantités, il vaudrait mieux prendre tout en compte.

**Comment by paulgirard** [comment]
On tente de supprimer le filtre des double account de l'import

**Comment by paulgirard** [comment]
![image](https://user-images.githubusercontent.com/193478/97994003-1b706880-1de5-11eb-963b-e5a697ed92aa.png)
Ok c'est bon les flux vides sont bien présents maintenant.
