### ISSUE TITLE
In "classification" only the first four matching products are in bold, even if there are more

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#211]
See http://toflit18.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_orthographic&selectedParent=product_source&queryGroup=amandes&queryItem=amandes.*co

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10850348/101179931-308e2080-364b-11eb-849a-6f78ab20ff13.png">

**Comment by paulgirard** [comment]
Highlight result in expanded group result does not use Regexp.

**Comment by gdaudin** [comment]
Cool.
