### ISSUE TITLE
FLOWS: Column width should be kept from page to page

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#212]

**Comment by gdaudin** [comment]
Hum... Cela ne semble pas bon non plus. Ou peut-être est-ce un autre bug.
Préprod, écran standard pour les flux. Je peux jouer avec la largeur de "Products" et cela reste de page en page.
Par contre, cela ne marche pas avec "value". Je ne peux qu’agrandir et pas réduire.
Souci supplémentaire : je ne peux pas ré-initialiser la taille des colonnes. Du mois j’ai essayé de sortir et de revenir. Je n’ai pas vidé la cache, mais je n’ai pas envie de le faire pour "si peu".

**Comment by paulgirard** [comment]
Problème lié à #195 en partie.
J'ai corrigé les scrolls bars et ai interdit les tailles de colonnes trop petites (mini 50px).
Il reste que quand on resize une colonne la largeur devient trop importante quand on bouge un peu la souris... Je ne peux pas corriger ça. Cependant maintenant si la colonne devient très large on peut toujours explorer et corriger avec les scrolls bars.

**Comment by gdaudin** [comment]
Salut ! J’arrive à scroller, mais pas à réduire la taille d’une colonne. Et en plus, la largeur ne se reset pas lorsqu’on enlève et remet la variable.

**Comment by gdaudin** [comment]
Par contre, la largeur est bien conservée de page en page.

**Comment by paulgirard** [comment]
- [ ] reset la largeur quand on ajoute/supprime la variable (faisable)
- [ ] problème de réduction de largeur (??)

**Comment by gdaudin** [comment]
On vit avec le bug de la lib (problème de réduction de largeur)
