### ISSUE TITLE
Beyond 6 curves, TIME SERIES duplicates the extra curves without an error warning

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#220]
See : http://toflit18.medialab.sciences-po.fr/#/exploration/indicators?lines=%5B%7B%22color%22%3A%22%2394B8B7%22%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%23C14F4C%22%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22color%22%3A%22%23504342%22%2C%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Flandre_et_autres_%E9tats_de_l%27Empereur%7Epartner_grouping%22%2C%22name%22%3A%22Flandre%20et%20autres%20%E9tats%20de%20l%27Empereur%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22color%22%3A%22%23A563B7%22%2C%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22France%7Epartner_grouping%22%2C%22name%22%3A%22France%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22color%22%3A%22%2385C85B%22%2C%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Hollande%7Epartner_grouping%22%2C%22name%22%3A%22Hollande%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22color%22%3A%22%23B89648%22%2C%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Italie%7Epartner_grouping%22%2C%22name%22%3A%22Italie%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Levant_et_Barbarie%7Epartner_grouping%22%2C%22name%22%3A%22Levant%20et%20Barbarie%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Nord%7Epartner_grouping%22%2C%22name%22%3A%22Nord%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Outre-mers%7Epartner_grouping%22%2C%22name%22%3A%22Outre-mers%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Portugal%7Epartner_grouping%22%2C%22name%22%3A%22Portugal%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%2C%7B%22partnerClassification%22%3A%22partner_grouping%22%2C%22partner%22%3A%5B%7B%22id%22%3A%22Suisse%7Epartner_grouping%22%2C%22name%22%3A%22Suisse%22%7D%5D%2C%22kind%22%3A%22import%22%2C%22sourceType%22%3A%22Best%20Guess%20national%20partner%22%7D%5D

**Comment by paulgirard** [comment]
Disable add line when there is already six lines with a tooltip that says maximum is 6

**Comment by gdaudin** [comment]
J’ai testé là : http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/indicators?lines=%5B%7B%22color%22%3A%22%23504342%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Chemical_products%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Chemical%20products%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%23A563B7%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Coton_threads_and_fabrics%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Coton%20threads%20and%20fabrics%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%23C14F4C%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Crude_materials%2C_inedible%2C_except_combustibles%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Crude%20materials%2C%20inedible%2C%20except%20combustibles%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%2385C85B%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Drinks_and_tobacco%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Drinks%20and%20tobacco%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%2394B8B7%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Leather%2C_wood_and_paper_products%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Leather%2C%20wood%20and%20paper%20products%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%2C%7B%22color%22%3A%22%23B89648%22%2C%22productClassification%22%3A%22product_sitc_simplEN%22%2C%22product%22%3A%5B%7B%22id%22%3A%22Oils%7Eproduct_sitc_simplEN%22%2C%22name%22%3A%22Oils%22%7D%5D%2C%22sourceType%22%3A%22Best%20Guess%20national%20product%20x%20partner%22%7D%5D et cela a l’air bon. Merci !
