### ISSUE TITLE
Metadata: You cannot filter by "Partner" when asking for type of data" partner

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#223]
I thought we had already treated that. So I think it is a bug. 
It would be useful to see what goes into "Italy" through time.

**Comment by gdaudin** [comment]
"No child classification exists"

**Comment by paulgirard** [comment]
Disabled and/or better message when it's not possible to filter on partner if there is no children.
![image](https://user-images.githubusercontent.com/193478/164646743-726f87c3-5bb0-474d-b3f2-e9f9cb182659.png)

**Comment by gdaudin** [comment]
C’est bon : on peut regarder le contenu de l’Italie au cours du temps. Voir http://toflit18-pprd.medialab.sciences-po.fr/#/exploration/meta?model=partner&dataType=partner_simplification&partnerClassification=partner_grouping&partners=%5B%22Italie%7Epartner_grouping%22%5D
