### ISSUE TITLE
in classification, when you move from one search box to another, erasing a search box does not work

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#225]
And the url stays as before (with text in both search boxes).
Difficult to reproduce, but quite frequent.
I think it is because you can erase a search box without clicking "search".
Solution : cliking one of the two search buttons should update both search box.

**Comment by paulgirard** [comment]
supprime le contenu d'un search box, le state du filtre n'est pas modifié. Du coup le search est toujours actif alors qu ele champs est vide. 
Soit on active une vérification auto du champs vide, soit et c'est mieux on modifie le state des deux champs search au cick sur l'un ou l'autre des boutons.

**Comment by gdaudin** [comment]
Je ne crois pas que cela marche. 
Manœuvre (dans la pprd) : 
- Je vais dans la page classification
- Je cherche froment à gauche : résultat attendu
- J’efface la fenêtre de recherche de gauche, je cherche seigle à droite : tous les filtres disparaissent (et j’ai à nouveau "drap" en haut à gauche par exemple).

**Comment by paulgirard** [comment]
En effet j'ai juste oublié le champs de gauche... 
C'est corrigé

**Comment by gdaudin** [comment]
Cool, cela a l’air d’être bon.
