### ISSUE TITLE
The quantities graph are broken in the Times Series view

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#228]

**Comment by gdaudin** [comment]
C’est quoi les commits de Joris Jourdain sur "staging" ? Faut-il les mettre en master ?

**Comment by paulgirard** [comment]
Je te laisse faire l'enquête de pourquoi en regardant dans ta version ce qui se passe. Tu utilise bien la classif des unit aussi de ton côté ? 

Oui il faut garder les commits de Joris.

**Comment by gdaudin** [comment]
Salut ! Bon, j’ai essayé en changeant du javascript (? je suppose). Commits fc56aa222934c4378b78c5bdd396857df11f0a1d et 95062d726b1537c4f6437513216c72c8bf31ee47 sur Toflit18_data. Mais no cigar : cela n’apparaît toujours pas. 

J’ai remplacé : 
} else if (row.normalizedUnit === "pièces") {
              update.properties.quantity_nbr =
                row.quantity * metric2Data.factor;

par
  } else if (row.normalizedUnit === "nombre") {
              update.properties.quantity_nbr =
                row.quantity * metric2Data.factor;

dans quantities.js

**Comment by gdaudin** [comment]
Paul a réglé cela via le commit a28e82a1f9f51b11a015edda740d472f0a708a20 dans toflit18_data
