### ISSUE TITLE
Le nombre de catégories classées ne se met pas à jour dans la page classification

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#229]
Exemple : Beaver au 7/02/2022. J’ai 21 108 simplifications classées, sur 22338  (toute Bdd dans le csv de classification). Pourtant, l’information donnée est 21256 classés sur 21257.

Si je me limite à la bdd Balance du Commerce, j’ai d’après mon dta, 989 non classés sur 18864 produits simplifiés.

**Comment by paulgirard** [comment]
![image](https://user-images.githubusercontent.com/193478/164644939-ef1b24e6-a48e-4e64-b453-a76e3a916147.png)

**Comment by gdaudin** [comment]
La somme du nombre d’item par groupe dans la vue classification n’est pas cohérente avec l’info de la colonne de gauche

**Comment by gdaudin** [comment]
Cela a l’air bon : merci !

**Comment by gdaudin** [comment]
Attends... Les métadonnées sont fausses pour les classifications "orthographiques". Voir : 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/10850348/185217845-3df3ade3-4f2b-472a-8969-e262db46f710.png">
http://toflit18-pprd.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_orthographic&selectedParent=product_source
mais 
http://toflit18.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_orthographic&selectedParent=product_sourcehttp://toflit18-pprd.medialab.sciences-po.fr/#/classification/browser?kind=product&selected=product_orthographic&selectedParent=product_source

**Comment by gdaudin** [comment]
Done
