### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by paulgirard** [medialab/toflit18#93]
# Colonne DATA 
- select product ou country
- select une classification cible parmi toutes (select avec représentation hiérarchique ou simple ?)
- infobox sur la classification sélectionnée
- select une classification parente de la précédente
- infobox sur la classification parente
- bouton "update" ?

# Colonne VIZ 
Liste de bloc contenant deux entêtes : 
- classification cible + une barre de filtrage
- classification parente + une barre de filtrage

Chaque bloc contient : 
- à gauche le nom d'un groupe de la classification cible
- à droite le nom des items de la classification parente agrégé par le groupe 

# colonne legend
Un texte explicatif ?

**Comment by paulgirard** [comment]
Il faut mettre à jour l'api pour que le deuxième sélecteur puisse marcher...

**Comment by jacomyal** [comment]
- Le search ne renvoie que X items par groupe (genre 5)
  - Lorsqu'on a une requête sur les items, l'API renvoie les X premiers items, en les ordonnant avec ceux qui ont matché d'abord
  - L'API renvoie un flag `match` à `true` pour les items matchant la requête
  - Une nouvelle route permet de récupérer les Y items à partir de `offset` pour un group donné

**Comment by paulgirard** [comment]
Server side done in #130

**Comment by paulgirard** [comment]
- [ ]  : titre des colonnes
- [ ] : sléecteur parents classification par défaut
- [ ] style des search input
- [ ] : bug refresh page on search click
- [ ] : pagination des groupes < > ?
